
# Site Settings
locale                   : "de-DE"
title                    : "Quasi ne Band"
title_separator          : "-"
subtitle                 : "100% Live 100% Sound"
name                     : "Quasi ne Band"
description              : "Homepage der Band 'Quasi ne Band'"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/"
logo                     : "/assets/images/Quasilogo.webp" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "Quasi ne Band" # overrides the website title displayed in the masthead, use " " for no title

atom_feed:
  hide                   : true # true, false (default)


# Site Footer
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://de-de.facebook.com/QuasiNeBand/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"


include:
  - _pages
exclude:
  - main.sh
  - Gemfile
  - Gemfile.lock

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
encoding: "utf-8"
markdown: kramdown

